export type VerificationStatus = "verified" | "review" | "error" | "excluded";

export type Analyzer = {
  id: string;
  rowNumber: number;
  laboratory: string;
  organization: string;
  balanceType: string;
  balanceHolderDetails: string;
  floor: string;
  address: string;
  level: string;
  direction: string;
  manufacturer: string;
  model: string;
  sourceManufacturer?: string;
  sourceModel?: string;
  sourceCapacity?: string;
  originalCapacity?: string;
  inventoryNumber: string;
  serials: string[];
  manufactureYear: string;
  commissioningDate: string;
  usefulLife: string;
  depreciation: string;
  bregisConnection: string;
  technicalStatus: string;
  responsiblePerson: string;
  note: string;
  status: VerificationStatus;
  verificationText: string;
  capacityPerHour: number | null;
  capacityUnit: "tests/hour" | "samples/hour" | null;
  includedInKpi: boolean;
  factIncluded: boolean;
  factInCalculation: number;
  monthlyCapacity: number;
  rowKpi: number | null;
  issue?: string;
  question?: string;
  sourceUrl?: string;
  powerComment?: string;
  reasonComment?: string;
  response?: string;
  confirmedBy?: string;
  confirmedAt?: string;
};

export type LaboratorySummary = {
  name: string;
  fact: number;
  kpi: number;
  capacityPerHour: number;
  monthlyCapacity: number;
  analyzers: number;
  reviewCount: number;
  errorCount: number;
  dataStatus: string;
};

export type DashboardData = {
  source: "google-sheets" | "fallback";
  updatedAt: string;
  totalKpi: number;
  totalFact: number;
  totalCapacityPerHour: number;
  totalMonthlyCapacity: number;
  totalAnalyzersInCapacity: number;
  laboratories: LaboratorySummary[];
  analyzers: Analyzer[];
};
